version: '3'
services:
  db:
    ports:
      - "3306:3306"

  backend:
    ports:
      - "8000:8000"

  frontend:
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_REDIRECT_URL=https://solid-dataspace-manager.com

  fuseki:
    ports:
      - "3030:3030"

  caddy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
