services:
  frontend:
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_REDIRECT_URL=http://localhost

  caddy:
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
