services:
  frontend:
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_REDIRECT_URL=https://solid-dataspace-manager.com

  caddy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
